heat_template_version: 2013-05-23

description: >
  Template for additional nodes in a Hadoop cluster

parameters:
  hadoop_security_group:
    type: string
    description: Security group passed from main template
  key_name:
    type: string
  image_id:
    type: string
  admin_user:
    type: string
  flavor:
    type: string
  public_net_id:
    type: string
  private_net_id:
    type: string
  private_subnet_id:
    type: string
  ssh_security_group:
    type: string
  server_name:
    type: string

resources:
  hadoop_data_server:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_name }
      admin_user: { get_param: admin_user }
      image: { get_param: image_id }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: hadoop_data_server_port }

  hadoop_data_server_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net_id }
      fixed_ips:
        - subnet_id: { get_param: private_subnet_id }
      security_groups: [{ get_param: hadoop_security_group }, { get_param: ssh_security_group }]

  hadoop_data_server_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: hadoop_data_server_port }

outputs:
  hadoop_node_private_ip:
    description: IP address of Hadoop Data Node in private network
    value: [{ get_attr: [ hadoop_data_server, first_address ] }, { get_attr: [ hadoop_data_server, name ] }]
  hadoop_node_public_ip:
    description: Floating IP address of Hadoop Data Node in public network
    value: [{ get_attr: [ hadoop_data_server_floating_ip, floating_ip_address ] }, { get_attr: [ hadoop_data_server, name ] }]
